language: generic
sudo: required
dist: trusty

env:
 - PYTEST_QT_API=pyqt4   PYTHON=python2.7
 - PYTEST_QT_API=pyqt4v2 PYTHON=python2.7
 - PYTEST_QT_API=pyside  PYTHON=python2.7

 - PYTEST_QT_API=pyqt4   PYTHON=python3.4
 - PYTEST_QT_API=pyqt4v2 PYTHON=python3.4
 - PYTEST_QT_API=pyside  PYTHON=python3.4
 - PYTEST_QT_API=pyqt5   PYTHON=python3.4

install:
 - sudo apt-get update

 # Xvfb / window manager
 - sudo apt-get install -y xvfb herbstluftwm

 # Qt
 - $PYTHON scripts/install-qt.py

 # Pip (3.4 does not have it by default)
 - wget https://bootstrap.pypa.io/get-pip.py
 - sudo $PYTHON get-pip.py

 # Dependencies
 - sudo $PYTHON -m pip install -U pytest tox coveralls

 # pytest-qt
 - sudo $PYTHON setup.py develop

before_script:
 - "export DISPLAY=:99.0"
 - start-stop-daemon --start --background --exec /usr/bin/Xvfb -- $DISPLAY -screen 0 1024x768x24
 - sleep 3 # give xvfb some time to start
 - "herbstluftwm &"
 - sleep 1

script:
 - catchsegv coverage run --source=pytestqt -m pytest tests
 - sudo tox -e lint
 - sudo chmod -R a+rw .

after_success:
 - coveralls

deploy:
  provider: pypi
  skip_upload_docs: true
  user: nicoddemus
  password:
    secure: Fql0uLFWz+D6p36BUm+2WB5tjUiuCkOFpU68Dnycn5cIRqZQuBzfNNZPVGHgIUGNZ5rC+rJC+edEvJoF2AB9cQ7kz86SzZuQHdEOwsnR4KQw2tkD5fw2BqH4bQ56SQ+UHAsyQAuDkjShHTrwSTJrzShIE5Poma5BqmqC4mRSgbI=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: pytest-dev/pytest-qt
    condition: $PYTEST_QT_API = pyqt5

