language: python
python:
  - "2.7"
before_script:
 - "export DISPLAY=:99.0"
 - "sh -e /etc/init.d/xvfb start"
 - sleep 3

env:
 - PYTEST_VERSION=2.4.2
 - PYTEST_VERSION=2.5.2

install:
 - sudo apt-get install -qq python-pyside
 - ln -s /usr/lib/python$TRAVIS_PYTHON_VERSION/dist-packages/PySide /home/travis/virtualenv/python$TRAVIS_PYTHON_VERSION/lib/python$TRAVIS_PYTHON_VERSION/site-packages/PySide -v
 - pip uninstall -y pytest
 - pip install pytest==$PYTEST_VERSION
  
script:
 - py.test
