language: c

dist: trusty

os:
  - linux

env:
# - PYTHON=27 PYTEST_QT_API=pyqt4
# - PYTHON=27 PYTEST_QT_API=pyside
# - PYTHON=34 PYTEST_QT_API=pyqt4
# - PYTHON=34 PYTEST_QT_API=pyside
 - PYTHON=34 PYTEST_QT_API=pyqt5

install:
 #- sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
 - sudo apt-get update -y
 # Qt
 - python scripts/install-qt.py

 # others
 #- sudo python -m pip install coveralls --use-wheel

before_script:
 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start
 - sleep 3


script:
 #- python setup.py develop
 #- catchsegv coverage run --source=pytestqt setup.py test
 - tox -e py$PYTHON-$PYTEST_QT_API

#after_success:
# - coveralls
