language: python
services: docker  # so we get Ubuntu Trusty with Python 3.4

python:
  - "2.7"
  - "3.4"

virtualenv:
  system_site_packages: true

matrix:
  allow_failures:
    # unfortunately couldn't find a reliable way to test pyqt5 on travis yet
    - env: PYTEST_VERSION=2.7.2 PYTEST_QT_API=pyqt5

env:
 - PYTEST_VERSION=2.7.2 PYTEST_QT_API=pyqt4
 - PYTEST_VERSION=2.7.2 PYTEST_QT_API=pyqt4v2
 - PYTEST_VERSION=2.7.2 PYTEST_QT_API=pyside
 - PYTEST_VERSION=2.7.2 PYTEST_QT_API=pyqt5

install:
 - sudo apt-get update

 # Xvfb
 - sudo apt-get install xvfb

 # Qt
 - python scripts/install-qt.py

 # PyTest
 - pip install -U pytest==$PYTEST_VERSION

 # others
 - pip install coveralls --use-wheel

script:
 - python setup.py develop
 - catchsegv xvfb-run coverage run --source=pytestqt setup.py test

after_success:
 - coveralls
