language: python
python:
  - "2.7"
  - "3.4"
before_script:
 - "export DISPLAY=:99.0"
 - "sh -e /etc/init.d/xvfb start"
 - sleep 3

env:
 - PYTEST_VERSION=2.5.2 PYTEST_QT_FORCE_PYQT=true
 - PYTEST_VERSION=2.5.2 PYTEST_QT_FORCE_PYQT=false

install:
 # PySide
 - if [[ $PYTEST_QT_FORCE_PYQT == 'false' ]]; then
 - pip install pyside
 - fi

 # PyQt4
 - if [[ $PYTEST_QT_FORCE_PYQT == 'true' ]]; then
 - pip install pyqt4
 - fi

 # PyTest
 - pip uninstall -y pytest
 - pip install pytest==$PYTEST_VERSION
  
script:
 - py.test
