language: python

python:
  - 2.7
  - 3.2
  
virtualenv:
  system_site_packages: true  

env:
 - PYTEST_VERSION=2.5.2 PYTEST_QT_FORCE_PYQT=true
 - PYTEST_VERSION=2.5.2 PYTEST_QT_FORCE_PYQT=false

install:
 # PySide
 - echo $TRAVIS_PYTHON_VERSION
 - if [[ "$PYTEST_QT_FORCE_PYQT" == "false" && "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
 -     sudo apt-get install -qq python-pyside;
 - elif [[ "$PYTEST_QT_FORCE_PYQT" == "false" && "$TRAVIS_PYTHON_VERSION" == "3.2" ]]; then
 -     sudo apt-get install -qq python3-pyside;
 - fi

 # PyQt4
 - if [[ "$PYTEST_QT_FORCE_PYQT" == "true" && "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
 -   sudo apt-get install -qq python-qt4
 - elif [[ "$PYTEST_QT_FORCE_PYQT" == "true" && "$TRAVIS_PYTHON_VERSION" == "3.2" ]]; then
 -   sudo apt-get install -qq python3-pyqt4
 - fi

 # PyTest
 - pip uninstall -y pytest
 - pip install pytest==$PYTEST_VERSION

before_script:
 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start
 - sleep 3

script:
 - python setup.py develop
 - py.test
