language: python

python:
  - 2.7
  - 3.2
  
virtualenv:
  system_site_packages: true  

env:
# - PYTEST_VERSION=2.6.4 PYTEST_QT_FORCE_PYQT=true
# - PYTEST_VERSION=2.6.4 PYTEST_QT_FORCE_PYQT=false
# - PYTEST_VERSION=2.7.0 PYTEST_QT_FORCE_PYQT=true
 - PYTEST_VERSION=2.7.0 PYTEST_QT_FORCE_PYQT=4
 - PYTEST_VERSION=2.7.0 PYTEST_QT_FORCE_PYQT=5

install:
 - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
 - sudo apt-get update
 
 # Qt
 - python install-qt.py

 # PyTest
 - pip uninstall -y pytest
 - pip install pytest==$PYTEST_VERSION

 # others
 - pip install coveralls --use-wheel

before_script:
 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start
 - sleep 3

script:
 - python setup.py develop
 - coverage run --source=pytestqt setup.py test

after_success:
 - coveralls
