language: python
python: "3.6"
sudo: required
dist: trusty

env:
  global:
      # used by ci-helpers
      - DEPS="pytest tox coveralls six"
      - MINICONDA_VERSION=latest

  matrix:
      - LINTING=1
      - PYTEST_QT_API=pyqt4   PYQT_PACKAGE="pyqt=4.*" PYTHON_VERSION=2.7
      - PYTEST_QT_API=pyqt4v2 PYQT_PACKAGE="pyqt=4.*" PYTHON_VERSION=2.7
      - PYTEST_QT_API=pyside  PYQT_PACKAGE="pyside=1.*" PYTHON_VERSION=2.7

      - PYTEST_QT_API=pyqt4   PYQT_PACKAGE="pyqt=4.*" PYTHON_VERSION=3.4
      - PYTEST_QT_API=pyqt4v2 PYQT_PACKAGE="pyqt=4.*" PYTHON_VERSION=3.4
      - PYTEST_QT_API=pyside  PYQT_PACKAGE="pyside=1.*" PYTHON_VERSION=3.4

      - PYTEST_QT_API=pyqt5   PYQT_PACKAGE="pyqt=5.*" PYTHON_VERSION=3.5
      - PYTEST_QT_API=pyside2   PYQT_PACKAGE="pyside2=2.*" PYTHON_VERSION=3.5

      - PYTEST_QT_API=pyqt5   PYQT_PACKAGE="pyqt=5.*" PYTHON_VERSION=3.6
      - PYTEST_QT_API=pyside2   PYQT_PACKAGE="pyside2=2.*" PYTHON_VERSION=3.6

matrix:
  # PySide2 crashes: #202
  allow_failures:
    - env: PYTEST_QT_API=pyside2   PYQT_PACKAGE="pyside2=2.*" PYTHON_VERSION=3.5
    - env: PYTEST_QT_API=pyside2   PYQT_PACKAGE="pyside2=2.*" PYTHON_VERSION=3.6

install:
  - |
    if [ $LINTING == "1" ]; then
      pip install -U pip
      pip install tox
    else
      # Xvfb / window manager
      sudo apt-get update
      sudo apt-get install -y xvfb herbstluftwm

      # Setup miniconda
      wget https://repo.continuum.io/miniconda/Miniconda3-${MINICONDA_VERSION}-Linux-x86_64.sh -O miniconda.sh
      bash miniconda.sh -b -p $HOME/miniconda
      export PATH="$HOME/miniconda/bin:$PATH"
      conda config --add channels conda-forge
      conda config --set always_yes yes --set changeps1 no
      conda create -n test --quiet python=${PYTHON_VERSION} ${DEPS} ${PYQT_PACKAGE}
      # pytest-xvfb installed via pip because not on conda-forge yet
      source activate test && pip install -e . pytest-xvfb
    fi

before_script:
 - "herbstluftwm &"
 - sleep 1

script:
  - |
    if [ $LINTING == "1" ]; then
      tox -e linting
    else
      source activate test && catchsegv coverage run --source=pytestqt -m pytest -v tests
    fi

after_success:
 - coveralls

deploy:
  provider: pypi
  skip_upload_docs: true
  user: nicoddemus
  distributions: sdist bdist_wheel
  password:
    secure: Fql0uLFWz+D6p36BUm+2WB5tjUiuCkOFpU68Dnycn5cIRqZQuBzfNNZPVGHgIUGNZ5rC+rJC+edEvJoF2AB9cQ7kz86SzZuQHdEOwsnR4KQw2tkD5fw2BqH4bQ56SQ+UHAsyQAuDkjShHTrwSTJrzShIE5Poma5BqmqC4mRSgbI=
  on:
    tags: true
    repo: pytest-dev/pytest-qt
    condition: $PYTEST_QT_API = pyqt5
