language: generic
sudo: required
dist: trusty

env:
 - PYTEST_QT_API=pyqt4   PYQT_PACKAGE="pyqt==4.*" PYTHON_VERSION=2.7
 - PYTEST_QT_API=pyqt4v2 PYQT_PACKAGE="pyqt==4.*" PYTHON_VERSION=2.7
 - PYTEST_QT_API=pyside  PYQT_PACKAGE="pyside==1.*" PYTHON_VERSION=2.7

 - PYTEST_QT_API=pyqt4   PYQT_PACKAGE="pyqt==4.*" PYTHON_VERSION=3.4
 - PYTEST_QT_API=pyqt4v2 PYQT_PACKAGE="pyqt==4.*" PYTHON_VERSION=3.4
 - PYTEST_QT_API=pyside  PYQT_PACKAGE="pyside==1.*" PYTHON_VERSION=3.4
 - PYTEST_QT_API=pyqt5   PYQT_PACKAGE="pyqt==5.*" PYTHON_VERSION=3.4

install:
 - sudo apt-get update

 # Xvfb / window manager
 - sudo apt-get install -y xvfb herbstluftwm

 # Setup miniconda 
 - git clone --depth 1 git://github.com/astropy/ci-helpers.git
 - export SETUP_XVFB=true && source ci-helpers/travis/setup_conda.sh

 # Dependencies
 - conda create -c conda-forge -n test-env -y pytest tox coveralls ${PYQT_PACKAGE} python=${PYTHON_VERSION}
 - source activate test-env && pip install -e .


before_script:
 - "herbstluftwm &"
 - sleep 1

script:
 - source activate test-env && catchsegv coverage run --source=pytestqt -m pytest tests
 # for some reason tox doesn't get installed with a u+x flag
 - | 
     chmod u+x /home/travis/miniconda/envs/test-env/bin/tox 
     /home/travis/miniconda/envs/test-env/bin/tox -e lint

after_success:
 - coveralls

deploy:
  provider: pypi
  skip_upload_docs: true
  user: nicoddemus
  password:
    secure: Fql0uLFWz+D6p36BUm+2WB5tjUiuCkOFpU68Dnycn5cIRqZQuBzfNNZPVGHgIUGNZ5rC+rJC+edEvJoF2AB9cQ7kz86SzZuQHdEOwsnR4KQw2tkD5fw2BqH4bQ56SQ+UHAsyQAuDkjShHTrwSTJrzShIE5Poma5BqmqC4mRSgbI=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: pytest-dev/pytest-qt
    condition: $PYTEST_QT_API = pyqt5

