language: python
sudo: required
dist: trusty

python:
  - "2.7"
  - "3.4"

virtualenv:
  system_site_packages: true

matrix:
  exclude:
    - env: PYTEST_QT_API=pyqt5
      python: "2.7"

env:
 - PYTEST_QT_API=pyqt4
 - PYTEST_QT_API=pyqt4v2
 - PYTEST_QT_API=pyside
 - PYTEST_QT_API=pyqt5

install:
 - sudo apt-get update

 # Xvfb
 - sudo apt-get install -y xvfb

 # Qt
 - python scripts/install-qt.py

 # PyTest
 - pip install -U pytest

 # Tox
 - pip install -U tox

 # others
 - pip install coveralls --use-wheel

script:
 - python setup.py develop
 # change screen size and depth in attempt to fix waitActive test (#160)
 - catchsegv xvfb-run --server-args="-screen 0 640x480x24" coverage run --source=pytestqt setup.py test
 - tox -e lint

after_success:
 - coveralls
